name: neospring CI

env:
  GO_VERSION: 1.19

on:
  pull_request:
  push:
  schedule:
    # every day at 8 AM
    - cron: "0 8 * * *"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build .

  golangci-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Check: golangci-lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49

  program_starts:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Go: Download modules"
        run: go mod download

      - name: "Go: Build"
        run: go build .

      - name: Check programs start
        # The process responds gracefully to `SIGTERM` by shutting itself down,
        # thus producing an exit code of 0 when things are working.
        run: |
          ( sleep 5 && killall -SIGTERM neospring ) &
          ./neospring

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Go: Download modules"
        run: go mod download

      - name: "Go: Test"
        run: go test ./... -race

